### ISSUE TITLE
best way to add favicon to project?

### ISSUE THREAD

**Issue by lljr** [ChangoMan/gatsby-starter-dimension#8]
Hi, I tried adding a favicon to the project in line 154 on `./src/layouts/index.js` file by inserting ->  `<link rel="icon" type="image/x-icon" href="../../favicon.ico" />` with a `favicon.ico` on my root dir... but with no success...

**Comment by avocadoras** [comment]
@erwintj thanks! it's working. not sure why Helmet is there?
